import {localStorageAdapter} from "../storage/localStorageAdapter.js";
import {saveGalleryMedia,deleteGalleryMedia} from "../blobStore.js";
const KEY="mykis.galleryAlbums.v1";
const now=()=>new Date().toISOString();
const normalize=a=>({...a,mediaItems:Array.isArray(a.mediaItems)?a.mediaItems:(a.images||[]).map(x=>({...x,type:"image"})),allowDownload:a.allowDownload===true});
export const galleryService={
  list(){const rows=localStorageAdapter.read(KEY,[]).map(normalize);localStorageAdapter.write(KEY,rows);return rows;},
  get(id){return this.list().find(a=>a.id===id)||null;},
  canView(album,{account,employee,enrollments=[]}){if(!album||album.status!=="published"||account?.role!=="employee")return false;const enrollment=enrollments.find(e=>e.courseId===album.courseId);return album.visibility==="all_employees"||(album.visibility==="course_assignees"&&!!enrollment)||(album.visibility==="course_completed"&&enrollment?.status==="completed")||(album.visibility==="departments"&&(album.departmentNames||[]).includes(employee?.department))||(album.visibility==="specific_employees"&&(album.employeeAccountIds||[]).includes(account.id));},
  visibleFor(context){return this.list().filter(a=>this.canView(a,context));},
  save(data){const rows=this.list(),index=rows.findIndex(a=>a.id===data.id);const prior=index>=0?rows[index]:null;const album={id:prior?.id||crypto.randomUUID(),title:String(data.title||"").trim(),description:String(data.description||""),eventDate:data.eventDate||"",location:data.location||"",courseId:data.courseId||"",departmentNames:data.departmentNames||[],employeeAccountIds:data.employeeAccountIds||[],visibility:data.visibility||"all_employees",status:data.status||"draft",coverMediaId:data.coverMediaId||prior?.coverMediaId||"",allowDownload:data.allowDownload===true,createdBy:prior?.createdBy||data.createdBy,createdAt:prior?.createdAt||now(),updatedAt:now(),mediaItems:prior?.mediaItems||[]};if(!album.title)return {ok:false,error:"title_required"};if(index>=0)rows[index]=album;else rows.unshift(album);localStorageAdapter.write(KEY,rows);return {ok:true,album};},
  async addFiles(albumId,files){const album=this.get(albumId);if(!album)return {ok:false,errors:["album_not_found"]};const saved=[],errors=[];for(const file of files){try{const blobId=await saveGalleryMedia(file);saved.push({id:crypto.randomUUID(),albumId,type:file.type.startsWith("video/")?"video":"image",blobId,fileName:file.name,mimeType:file.type,fileSize:file.size,caption:"",alt:album.title,takenAt:"",order:album.mediaItems.length+saved.length+1,createdAt:now()});}catch(error){errors.push({fileName:file.name,error:error.message});}}album.mediaItems.push(...saved);if(!album.coverMediaId&&saved[0])album.coverMediaId=saved[0].id;this.save({...album});return {ok:saved.length>0,saved,errors};},
  addYoutube(albumId,url,caption=""){const album=this.get(albumId),id=normalizeYoutube(url);if(!album||!id)return {ok:false,error:"invalid_youtube"};album.mediaItems.push({id:crypto.randomUUID(),albumId,type:"youtube",youtubeVideoId:id,caption,alt:caption||album.title,order:album.mediaItems.length+1,createdAt:now()});if(!album.coverMediaId)album.coverMediaId=album.mediaItems.at(-1).id;this.save(album);return {ok:true};},
  async removeMedia(albumId,mediaId){const album=this.get(albumId),item=album?.mediaItems.find(x=>x.id===mediaId);if(!item)return false;if(item.blobId)await deleteGalleryMedia(item.blobId);album.mediaItems=album.mediaItems.filter(x=>x.id!==mediaId);if(album.coverMediaId===mediaId)album.coverMediaId=album.mediaItems[0]?.id||"";this.save(album);return true;},
};
function normalizeYoutube(value){const s=String(value||"").trim();if(/^[\w-]{11}$/.test(s))return s;return s.match(/(?:youtube\.com\/(?:watch\?(?:.*&)?v=|embed\/|shorts\/)|youtu\.be\/)([\w-]{11})/)?.[1]||"";}
