import {localStorageAdapter} from "../storage/localStorageAdapter.js";
import {getCourseById,getEnrollmentsByCourseId,getAccountById,addSecurityAuditLog,createNotification} from "../mockDatabase.js";
const SESSIONS="mykis.offlineSessions.v1",REGISTRATIONS="mykis.sessionRegistrations.v1",REVISION="mykis.trainingDataRevision.v1";
const now=()=>new Date().toISOString();
const bump=()=>localStorageAdapter.write(REVISION,Number(localStorageAdapter.read(REVISION,0))+1);
export const offlineTrainingService={
  getRevision(){return Number(localStorageAdapter.read(REVISION,0));},
  listSessions({courseId="",status=""}={}){return localStorageAdapter.read(SESSIONS,[]).filter(x=>(!courseId||x.courseId===courseId)&&(!status||x.status===status)).sort((a,b)=>a.startAt.localeCompare(b.startAt));},
  getSession(id){return this.listSessions().find(x=>x.id===id)||null;},
  saveSession(data,actorAccountId){if(getAccountById(actorAccountId)?.role!=="hr")return {ok:false,error:"forbidden"};const start=new Date(data.startAt),end=new Date(data.endAt),deadline=data.registrationDeadline?new Date(data.registrationDeadline):null;if(!data.courseId||!String(data.title||"").trim()||!Number.isFinite(+start)||!Number.isFinite(+end)||end<=start)return {ok:false,error:"invalid_time"};if(data.locationType==="onsite"&&!String(data.locationName||"").trim())return {ok:false,error:"location_required"};if(deadline&&deadline>=start)return {ok:false,error:"invalid_deadline"};const rows=localStorageAdapter.read(SESSIONS,[]),index=rows.findIndex(x=>x.id===data.id);const prior=index>=0?rows[index]:null;const row={id:prior?.id||crypto.randomUUID(),courseId:data.courseId,title:String(data.title).trim(),description:String(data.description||""),trainerName:String(data.trainerName||""),trainerType:data.trainerType||"internal",startAt:start.toISOString(),endAt:end.toISOString(),timezone:"Asia/Ho_Chi_Minh",locationType:data.locationType||"onsite",locationName:String(data.locationName||""),address:String(data.address||""),meetingUrl:String(data.meetingUrl||""),capacity:Math.max(1,Math.floor(Number(data.capacity)||1)),registrationDeadline:deadline?.toISOString()||"",attendanceRequired:data.attendanceRequired!==false,status:data.status||"scheduled",attendanceLocked:prior?.attendanceLocked||false,createdBy:prior?.createdBy||actorAccountId,createdAt:prior?.createdAt||now(),updatedAt:now()};if(index>=0)rows[index]=row;else rows.push(row);localStorageAdapter.write(SESSIONS,rows);bump();addSecurityAuditLog({action:prior?"Update offline session":"Create offline session",targetAccountId:row.id,targetEmployeeName:getCourseById(row.courseId)?.title||row.courseId,description:row.title});return {ok:true,session:row};},
  registrations(sessionId=""){return localStorageAdapter.read(REGISTRATIONS,[]).filter(x=>!sessionId||x.sessionId===sessionId);},
  getRegistration(sessionId,accountId){return this.registrations(sessionId).find(x=>x.accountId===accountId)||null;},
  ensureInvitations(sessionId){const session=this.getSession(sessionId);if(!session)return [];const rows=localStorageAdapter.read(REGISTRATIONS,[]);for(const enrollment of getEnrollmentsByCourseId(session.courseId)){if(!rows.some(x=>x.sessionId===sessionId&&x.accountId===enrollment.accountId))rows.push({id:crypto.randomUUID(),sessionId,accountId:enrollment.accountId,responseStatus:"pending",responseReason:"",respondedAt:"",attendanceStatus:"not_marked",checkInAt:"",checkOutAt:"",attendedSeconds:0,attendanceNote:"",markedBy:"",markedAt:"",createdAt:now(),updatedAt:now()});}localStorageAdapter.write(REGISTRATIONS,rows);return rows.filter(x=>x.sessionId===sessionId);},
  respond(sessionId,accountId,responseStatus,responseReason=""){const session=this.getSession(sessionId);if(!session||session.status!=="scheduled"||!["attending","busy","declined"].includes(responseStatus))return {ok:false,error:"invalid_response"};if(session.registrationDeadline&&new Date()>new Date(session.registrationDeadline))return {ok:false,error:"deadline_passed"};this.ensureInvitations(sessionId);const rows=localStorageAdapter.read(REGISTRATIONS,[]),index=rows.findIndex(x=>x.sessionId===sessionId&&x.accountId===accountId);if(index<0)return {ok:false,error:"not_invited"};rows[index]={...rows[index],responseStatus,responseReason:String(responseReason||""),respondedAt:now(),updatedAt:now()};localStorageAdapter.write(REGISTRATIONS,rows);bump();createNotification({type:"offline_response",targetAccountId:accountId,title:responseStatus==="attending"?"Đã xác nhận tham gia":"Đã ghi nhận báo bận",body:session.title,actionUrl:`/dashboard/calendar?sessionId=${sessionId}`});return {ok:true,registration:rows[index]};},
  markAttendance(sessionId,accountId,data,actorAccountId){const session=this.getSession(sessionId);if(!session||getAccountById(actorAccountId)?.role!=="hr")return {ok:false,error:"forbidden"};if(session.attendanceLocked)return {ok:false,error:"attendance_locked"};this.ensureInvitations(sessionId);const rows=localStorageAdapter.read(REGISTRATIONS,[]),index=rows.findIndex(x=>x.sessionId===sessionId&&x.accountId===accountId);if(index<0)return {ok:false,error:"not_found"};const status=data.attendanceStatus;if(!["not_marked","attended","partial","absent","excused"].includes(status))return {ok:false,error:"invalid_status"};const scheduled=Math.max(0,(new Date(session.endAt)-new Date(session.startAt))/1000);let seconds=0;if(status==="attended"||status==="partial"){const checkIn=data.checkInAt?new Date(data.checkInAt):null,checkOut=data.checkOutAt?new Date(data.checkOutAt):null;if(checkIn&&checkOut&&checkOut>checkIn)seconds=Math.min(scheduled,(checkOut-checkIn)/1000);else seconds=Math.min(scheduled,Math.max(0,Number(data.attendedMinutes??(status==="attended"?scheduled/60:0))*60));}rows[index]={...rows[index],attendanceStatus:status,checkInAt:data.checkInAt||"",checkOutAt:data.checkOutAt||"",attendedSeconds:Math.round(seconds),attendanceNote:String(data.attendanceNote||""),markedBy:actorAccountId,markedAt:now(),updatedAt:now()};localStorageAdapter.write(REGISTRATIONS,rows);bump();addSecurityAuditLog({action:"Mark attendance",targetAccountId:accountId,targetEmployeeName:getAccountById(accountId)?.fullName||accountId,description:`${session.title}: ${status}, ${Math.round(seconds/60)} minutes`});return {ok:true,registration:rows[index]};},
};
