import {getCourseContent,getContentProgress,getQuizAttemptsByAccountId,getAccounts,getCourses,getEnrollments} from "../mockDatabase.js";
import {offlineTrainingService} from "./offlineTrainingService.js";
const cache=new Map();
const inRange=(value,from,to)=>{const t=new Date(value).getTime();return Number.isFinite(t)&&(!from||t>=new Date(from).getTime())&&(!to||t<=new Date(to).getTime());};
export function mergeTimeRanges(ranges=[]){const clean=ranges.map(r=>[Math.max(0,Number(r[0])||0),Math.max(0,Number(r[1])||0)]).filter(([a,b])=>b>a).sort((a,b)=>a[0]-b[0]);const merged=[];for(const range of clean){const last=merged.at(-1);if(last&&range[0]<=last[1])last[1]=Math.max(last[1],range[1]);else merged.push([...range]);}return merged;}
export function calculateEmployeeTrainingTime(accountId,{dateFrom="",dateTo=""}={}){const revision=offlineTrainingService.getRevision(),key=`${accountId}|${dateFrom}|${dateTo}|${revision}`;if(cache.has(key))return cache.get(key);let onlineSeconds=0,offlineSeconds=0;const breakdown=[];for(const enrollment of getEnrollments().filter(e=>e.accountId===accountId)){let courseSeconds=0;const states=getContentProgress(accountId,enrollment.courseId);for(const content of getCourseContent(enrollment.courseId)){const state=states.find(x=>x.contentId===content.id);if(!state||!inRange(state.completedAt||state.lastActivityAt,dateFrom,dateTo))continue;let seconds=0;if(content.type==="slide")seconds=(content.slides||[]).reduce((sum,slide)=>sum+Math.min(Number(state.metadata?.slides?.[slide.id]?.viewedSeconds||0),Number(slide.minimumViewSeconds||content.minimumDurationSeconds||0)),0);else if(content.type==="video"){const ranges=state.metadata?.watchedRanges;seconds=Array.isArray(ranges)?mergeTimeRanges(ranges).reduce((s,[a,b])=>s+b-a,0):Math.max(0,Number(state.activeSeconds)||0);const cap=Number(state.metadata?.durationSeconds||0);if(cap>0)seconds=Math.min(seconds,cap);}else seconds=Math.max(0,Number(state.activeSeconds)||0);courseSeconds+=seconds;}for(const attempt of getQuizAttemptsByAccountId(accountId).filter(a=>a.courseId===enrollment.courseId&&a.submittedAt&&inRange(a.submittedAt,dateFrom,dateTo))){const quizCap=Math.max(0,Number(attempt.durationSeconds)||0);courseSeconds+=quizCap;}courseSeconds=Math.round(Math.max(0,courseSeconds));if(courseSeconds){onlineSeconds+=courseSeconds;breakdown.push({sourceType:"online",courseId:enrollment.courseId,seconds:courseSeconds});}}
  const sessions=new Map(offlineTrainingService.listSessions().map(s=>[s.id,s]));const seen=new Set();let attendedSessionCount=0;for(const registration of offlineTrainingService.registrations().filter(r=>r.accountId===accountId)){if(seen.has(registration.sessionId)||!["attended","partial"].includes(registration.attendanceStatus))continue;seen.add(registration.sessionId);const session=sessions.get(registration.sessionId);if(!session||session.status!=="completed"||new Date(session.endAt)>new Date()||!inRange(session.endAt,dateFrom,dateTo))continue;const scheduled=Math.max(0,(new Date(session.endAt)-new Date(session.startAt))/1000),seconds=Math.min(scheduled,Math.max(0,Number(registration.attendedSeconds)||0));if(seconds){offlineSeconds+=seconds;attendedSessionCount++;breakdown.push({sourceType:"offline",courseId:session.courseId,sessionId:session.id,seconds});}}
  const totalSeconds=Math.round(onlineSeconds+offlineSeconds),result={onlineSeconds:Math.round(onlineSeconds),offlineSeconds:Math.round(offlineSeconds),totalSeconds,totalMinutes:Math.round(totalSeconds/60),totalHours:Math.round(totalSeconds/360)/10,completedCourseCount:getEnrollments().filter(e=>e.accountId===accountId&&e.status==="completed").length,attendedSessionCount,breakdown};cache.set(key,result);return result;}
export function getCompanyTrainingAnalytics(options={}){const active=getAccounts().filter(a=>a.role==="employee"&&a.accountStatus==="active"),rows=active.map(a=>({account:a,training:calculateEmployeeTrainingTime(a.id,options)})),totalSeconds=rows.reduce((s,x)=>s+x.training.totalSeconds,0),onlineSeconds=rows.reduce((s,x)=>s+x.training.onlineSeconds,0),offlineSeconds=rows.reduce((s,x)=>s+x.training.offlineSeconds,0),sessions=offlineTrainingService.listSessions(),regs=offlineTrainingService.registrations(),required=regs.length,attended=regs.filter(r=>["attended","partial"].includes(r.attendanceStatus)).length,confirmed=regs.filter(r=>r.responseStatus==="attending").length,noShow=regs.filter(r=>r.responseStatus==="attending"&&r.attendanceStatus==="absent").length;return {employees:active.length,totalSeconds,onlineSeconds,offlineSeconds,averageSeconds:active.length?Math.round(totalSeconds/active.length):0,totalSessions:sessions.length,cancelledSessions:sessions.filter(s=>s.status==="cancelled").length,busyCount:regs.filter(r=>r.responseStatus==="busy").length,attendanceRate:required?Math.round(attended/required*100):0,noShowRate:confirmed?Math.round(noShow/confirmed*100):0,rows};}
export function formatTrainingDuration(seconds,locale="vi",compact=false){const safe=Math.max(0,Number(seconds)||0),hours=safe/3600;if(compact){const value=new Intl.NumberFormat(locale==="kr"?"ko-KR":locale==="en"?"en-US":"vi-VN",{maximumFractionDigits:1}).format(hours);return locale==="kr"?`${value}시간`:locale==="en"?`${value} hours`:`${value} giờ`;}const h=Math.floor(safe/3600),m=Math.round((safe%3600)/60);return locale==="kr"?`${h}시간 ${m}분`:locale==="en"?`${h} hr ${m} min`:`${h} giờ ${m} phút`;}
