const DB_NAME="mykis-learning-assets",STORE="course-images",PHOTO_STORE="employee-photos",MEDIA_STORE="gallery-media";
function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,3);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(STORE))request.result.createObjectStore(STORE);if(!request.result.objectStoreNames.contains(PHOTO_STORE))request.result.createObjectStore(PHOTO_STORE);if(!request.result.objectStoreNames.contains(MEDIA_STORE))request.result.createObjectStore(MEDIA_STORE);};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
export async function saveCourseImage(file){if(!file||!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5242880)throw new Error("invalid_image");const id=`course-image-${Date.now()}-${Math.random().toString(36).slice(2)}`,db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(file,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();return id;}
export async function getCourseImage(id){if(!id)return null;const db=await openDb(),blob=await new Promise((resolve,reject)=>{const request=db.transaction(STORE).objectStore(STORE).get(id);request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error);});db.close();return blob;}
export async function saveEmployeePhoto(file){if(!file||!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5242880)throw new Error("invalid_image");const id=`employee-photo-${Date.now()}-${Math.random().toString(36).slice(2)}`,db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(PHOTO_STORE,"readwrite");tx.objectStore(PHOTO_STORE).put(file,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();return id;}
export async function getEmployeePhoto(id){if(!id)return null;const db=await openDb(),blob=await new Promise((resolve,reject)=>{const request=db.transaction(PHOTO_STORE).objectStore(PHOTO_STORE).get(id);request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error);});db.close();return blob;}
export async function deleteEmployeePhoto(id){if(!id)return;const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(PHOTO_STORE,"readwrite");tx.objectStore(PHOTO_STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();}
export async function saveGalleryMedia(file){const allowed=["image/jpeg","image/png","image/webp","video/mp4","video/webm"];const max=file?.type?.startsWith("video/")?104857600:10485760;if(!file||!allowed.includes(file.type)||file.size>max)throw new Error(file?.size>max?"file_too_large":"invalid_media");const id=`gallery-${Date.now()}-${crypto.randomUUID?.()||Math.random().toString(36).slice(2)}`;const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(MEDIA_STORE,"readwrite");tx.objectStore(MEDIA_STORE).put(file,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();return id;}
export async function getGalleryMedia(id){if(!id)return null;const db=await openDb();const value=await new Promise((resolve,reject)=>{const req=db.transaction(MEDIA_STORE).objectStore(MEDIA_STORE).get(id);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error);});db.close();return value;}
export async function deleteGalleryMedia(id){if(!id)return;const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(MEDIA_STORE,"readwrite");tx.objectStore(MEDIA_STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();}
